<?php
/*
 * @Author:    Nathan Chick (nathan.chick@deploy.co.uk)
 * @Copyright: 2024 Deploy Ecommerce (https://www.deploy.co.uk/)
 * @Package:   DeployEcommerce_BuilderIO
 */


/**
 * @var $block \eployEcommerce\BuilderIO\Block\System\Config\Content
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div style="padding: 16px; border: 2px solid #CCC; background: #fafafa">
    Workspaces are mapped to stores not websites, please select your store to connect to Builder.io
</div>
