<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Rule\Block\Conditions $block */
?>

<div class="rule-conditions">
    <div id="<?= $block->getHtmlId() ?>" class="rule-tree">
        <div class="rule-tree-header">
            <div class="rule-tree-header-title">
                <?= $escaper->escapeHtml(__('Conditions')) ?>
            </div>
            <div class="rule-tree-header-actions">
                <button
                    type="button"
                    class="action-add"
                    id="<?= $block->getNewChildUrl() ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Add')) ?>">
                    <span><?= $escaper->escapeHtml(__('Add')) ?></span>
                </button>
            </div>
        </div>
        <div class="rule-tree-wrapper">
            <?= $block->getConditions()->asHtmlRecursive() ?>
        </div>
    </div>
</div>

<input type="hidden" name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>" value="<?= $escaper->escapeHtmlAttr($block->getConditions()->asArray(true)) ?>" data-form-part="<?= $escaper->escapeHtmlAttr($block->getFormName()) ?>"/>

<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm',
    'prototype'
], function(jQuery, confirmation){

//<![CDATA[
var <?= $block->getJsFormObject() ?> = new VarienForm('<?= $block->getFormName() ?>');
var rule_conditions_fieldset = {
    id: '<?= $block->getHtmlId() ?>',
    newChildUrl: '<?= $escaper->escapeUrl($block->getNewChildUrl()) ?>',
    removeUrl: '<?= $escaper->escapeUrl($block->getRemoveUrl()) ?>',
    form: <?= $block->getJsFormObject() ?>,
    canShow: 1,
    childCount: 0,
    show: function () {
        if (!this.canShow) {
            return;
        }
        Element.show(this.id);
        this.canShow = 0;
    },
    hide: function () {
        Element.hide(this.id);
        this.canShow = 1;
    },
    remove: function (elem) {
        if (elem.parentNode && elem.parentNode.parentNode) {
            elem = elem.parentNode.parentNode;
            var parent = elem.parentNode;
            parent.removeChild(elem);
            this.updateElement(parent);
        }
    },
    add: function () {
        this.childCount++;
        var url = this.newChildUrl.replace(/__index__/g, this.childCount);
        new Ajax.Request(url, {
            evalScripts: true,
            onSuccess: function(transport) {
                var newElem = transport.responseText;
                var re = /(<script.*?>)((\n|\r|.)*?)(<\/script>)/im;
                var match = newElem.match(re);
                if (match) {
                    newElem = newElem.replace(re, '');
                }
                var wrapper = document.createElement('div');
                wrapper.innerHTML = newElem;
                var newElement = wrapper.firstChild;

                var list = $(this.id).select('ul.rule-param-children')[0];
                list.appendChild(newElement);

                if (match) {
                    eval(match[2]);
                }
            }.bind(this)
        });
    },
    updateElement: function (elem) {
        if (elem.up('li.rule-param-wait')) {
            elem.up('li.rule-param-wait').removeClassName('rule-param-wait');
        }
    }
};
window.rule_conditions_fieldset = rule_conditions_fieldset;
//]]>

});
</script>
