<?php
/*
 * @Author:    Nathan Chick (nathan.chick@deploy.co.uk)
 * @Copyright: 2024 Deploy Ecommerce (https://www.deploy.co.uk/)
 * @Package:   DeployEcommerce_BuilderIO
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use DeployEcommerce\BuilderIO\ViewModel\Preview\Page;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var Page $viewModel
 */
$viewModel = $block->getViewModel();
?>
<builder-component
    model="<?= $escaper->escapeHtmlAttr($viewModel->getModelName()); ?>"
    api-key="<?= $escaper->escapeHtmlAttr($viewModel->getApiKey()); ?>"
></builder-component>
